---
title: "Additional Dataset Exploration"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
business_data <- read.csv("business_msa_data.csv")
data <- read.csv("priv_pay_data_with_hospital.csv")

econ_data <- read.csv("ACSST1Y2021.S1811-2022-10-18T015247.csv")

```


# Economic Characteristics


* Had issues downloading the S1811 dataset. Will discuss with Ryan to look into this more


```{r, echo = FALSE, warning = FALSE, message = FALSE}


```



# Total Employment

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA}

total_employment <- business_data %>%
  filter(naics == "------") %>%
  select(msa, emp, ap)

msa_pay_data <- data %>%
  group_by(msa) %>%
  summarise(msa_priv_pay_mean = weighted.mean(priv_pay_mean, priv_count, na.rm = T),
            msa_priv_pay_median = median(priv_pay_median, priv_count, na.rm = T))

full_data <- left_join(msa_pay_data, total_employment, by = "msa")

cor(full_data, use = "complete.obs")

ggplot(data = full_data, aes(x = emp, y = msa_priv_pay_mean)) + geom_point() +
  labs(title = "Private Payout Mean by Total Employment of MSA",
       x = "Total Employment",
       y = "Private Payout Mean (by MSA)")
ggplot(data = full_data, aes(x = ap, y = msa_priv_pay_mean)) + geom_point() +
  labs(title = "Private Payout Mean by Annual Payroll of MSA",
       x = "Annual Payroll",
       y = "Private Payout Mean (by MSA)")




```


* Not seeing much correlation between MSA employment or annual payroll with private payments
* Seems more logical to use population rather than employment or annual payroll if we choose to use this type of feature in the model