---
title: "Threshold Impact Assessment"
author: "Ryan Rogers"
date: "11/2/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(randomForest)
library(MLmetrics)
source(file = "../../Common_Functions/processing_functions.R") # import of data_split transformation
source(file = "../../Common_Functions/baseline_model.R") # import of baseline model
```

## Modeling with threshold 50 number of claims

First version will look at a threshold of >= 50.

```{r, warning = FALSE, message = FALSE}
data <- read.csv("../../Data_Files/JnJ_Files/priv_mcare_f_pay_2022Oct18.csv")
hospital_data <- read.csv("../../Data_Files/JnJ_Files/Hospital_Master_Sheet.csv")
```

```{r, warning = FALSE, message = FALSE}
data$index  <- 1:nrow(data)

# Hospital data aggregation - validated for sameness
hospitals_msa <- hospital_data %>% aggregate_hospital_features()

# Data split into model data and predict - varies from original slightly
split_dataset <- data %>% data_split(count_thresh = 49)
working_set <- split_dataset[[1]]
predict_set <- split_dataset[[2]]

model_data <- left_join(working_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(working_set)

predict_data <- left_join(predict_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(predict_set)

# Train test split
train_test_data <- model_data %>% train_test_split(proportion_train = 0.8)
rm(model_data)

train <- train_test_data[[1]]
test <- train_test_data[[2]]

clean_train <- train %>% select(-index)
clean_test <- test %>% select(-index)
```

```{r, warning = FALSE, message = FALSE}
# Random Forest model

# Fit Random Forest Model on training data
Random_Forest <- baseline_rdm_forest(data = clean_train)

train_predict <- make_baseline_prediction(Random_Forest, clean_train)
rm(clean_train)

train_mape_percent = get_mape_percentage(train_predict)
```


```{r, warning = FALSE, message = FALSE}
varImpPlot(Random_Forest, bg = "aquamarine3")

```


```{r, warning = FALSE, message = FALSE}
test_predict <- make_baseline_prediction(Random_Forest, clean_test)
rm(clean_test)

test_mape_percent = get_mape_percentage(test_predict)
```

```{r}
cat("With Threshold >50 claims for training set:\n")
cat("Train MAPE:" , round(train_mape_percent, 2), "%\n")
cat("Test MAPE:" , round(test_mape_percent, 2), "%\n")
cat("Sample data points used: ", nrow(train), "\n")
cat("Number of MSAs represented: ", nrow(train_predict %>% distinct(CBSA_NAME)), "\n")
cat("Number of groups represented: ", nrow(train_predict %>% distinct(group)), "\n")
cat("Number of states represented: ", nrow(train_predict %>% distinct(State)), "\n")
orig_groups <- train_predict %>% distinct(group)
orig_groups$group_present = TRUE
orig_states <- train_predict %>% distinct(State)
orig_states$state_present = TRUE
```


## Modeling with threshold 35 (Full sample)

```{r, warning = FALSE, message = FALSE}
# Hospital data aggregation - validated for sameness
hospitals_msa <- hospital_data %>% aggregate_hospital_features()

# Data split into model data and predict - varies from original slightly
split_dataset <- data %>% data_split(count_thresh = 34)
working_set <- split_dataset[[1]]
predict_set <- split_dataset[[2]]

model_data <- left_join(working_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(working_set)

test$exists = TRUE
model_data <- left_join(model_data, (test %>% select(exists, index)), by = 'index') %>% filter(is.na(exists)) %>% select(-exists)
test <- test %>% select(-exists)

predict_data <- left_join(predict_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(predict_set)

# Train test split
train_test_data <- model_data %>% train_test_split(proportion_train = 1)
rm(model_data)

train <- train_test_data[[1]]

clean_train <- train %>% select(-index)
clean_test <- test %>% select(-index)
```

```{r, warning = FALSE, message = FALSE}
# Random Forest model

# Fit Random Forest Model on training data
Random_Forest <- baseline_rdm_forest(data = train)

train_predict <- make_baseline_prediction(Random_Forest, train)
rm(train)

train_mape_percent = get_mape_percentage(train_predict)
```


```{r, warning = FALSE, message = FALSE}
varImpPlot(Random_Forest, bg = "aquamarine3")

```


```{r, warning = FALSE, message = FALSE}
test_predict <- make_baseline_prediction(Random_Forest, test)
rm(test)

test_mape_percent = get_mape_percentage(test_predict)
```

```{r}
cat("With Threshold >34 claims for full training set:\n")
cat("Train MAPE:" , round(train_mape_percent, 2), "%\n")
cat("Test MAPE:" , round(test_mape_percent, 2), "%\n")
cat("Sample data points used: ", nrow(train_predict), "\n")
cat("Number of MSAs represented: ", nrow(train_predict %>% distinct(CBSA_NAME)), "\n")
cat("Number of groups represented: ", nrow(train_predict %>% distinct(group)), "\n")
cat("Number of states represented: ", nrow(train_predict %>% distinct(State)), "\n")
```


## Modeling with threshold 35 (Stratified Sample)

```{r, warning = FALSE, message = FALSE}
# Hospital data aggregation - validated for sameness
hospitals_msa <- hospital_data %>% aggregate_hospital_features()

# Data split into model data and predict - varies from original slightly
split_dataset <- data %>% data_split(count_thresh = 34)
working_set <- split_dataset[[1]]
predict_set <- split_dataset[[2]]

model_data <- left_join(working_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(working_set)

model_data$index <- 1:nrow(model_data)

predict_data <- left_join(predict_set, hospitals_msa, by = "msa")  %>%
  select(-priv_pay_mean, -priv_pay_iqr, -mcare_pay_mean, -mcare_pay_sd, -Urban, -msa)
rm(predict_set)

model_data <- left_join(model_data, orig_groups, by='group')
model_data <- left_join(model_data, orig_states, by='State')

model_data_selection <- model_data %>% filter(!is.na(group_present) & !is.na(state_present))

# Train test split
train <- model_data_selection %>%
  group_by(group, State) %>%
  sample_frac(size=0.6291, replace=FALSE)
train$is_train = TRUE

test <- left_join(model_data, (train %>% select(index, is_train)), by = c('index')) %>% filter(is.na(is_train))
test$State = test$State.x
test$group = test$group.x

train <- data.frame(train %>% select(-index, -group_present, -state_present, -is_train))
test <- data.frame(test %>% select(-index, -group_present, -state_present, -is_train, -State.x, -State.y, -group.x, -group.y) %>% filter(priv_count > 49))
```


```{r, warning = FALSE, message = FALSE}
# Random Forest model

# Fit Random Forest Model on training data
Random_Forest <- baseline_rdm_forest(data = train)

train_predict <- make_baseline_prediction(Random_Forest, train)
rm(train)

train_mape_percent = get_mape_percentage(train_predict)
```


```{r, warning = FALSE, message = FALSE}
varImpPlot(Random_Forest, bg = "aquamarine3")

```


```{r, warning = FALSE, message = FALSE}
test_predict <- make_baseline_prediction(Random_Forest, test)
rm(test)

test_mape_percent = get_mape_percentage(test_predict)
```

```{r}
cat("With Threshold >34 claims for regular training set:\n")
cat("Train MAPE:" , round(train_mape_percent, 2), "%\n")
cat("Test MAPE:" , round(test_mape_percent, 2), "%\n")
cat("Sample data points used: ", nrow(train_predict), "\n")
cat("Number of MSAs represented: ", nrow(train_predict %>% distinct(CBSA_NAME)), "\n")
cat("Number of groups represented: ", nrow(train_predict %>% distinct(group)), "\n")
cat("Number of states represented: ", nrow(train_predict %>% distinct(State)), "\n")
```