---
title: "Data Preprocessing"
author: "Tyler Marshall"
date: "10/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}
data <- read.csv("priv_mcare_f_pay.csv")
hospital_data <- read.csv("Hospital_Master_Sheet.csv")

hospitals_msa <- hospital_data %>%
  group_by(MSA_CD) %>%
  summarise(Hospitals = n(),
            PctTeaching = sum(teaching == "YES")/n(),
            PctLargeHospital = sum(beds_grp == "500+")/n(),
            Urban = ifelse(sum(urban_rural == "URBAN")/n() == 1, "Urban","Rural"),
            PctPrivate = sum(ownership == "PRIVATE (NOT FOR PROFIT)" | ownership == "PRIVATE (FOR PROFIT)")/n()) %>%
  rename(msa = MSA_CD)

new_data <- data %>%
  filter(priv_pay_median >= 0 | is.na(priv_pay_median)) %>%
  filter(priv_count != 0)

new_data_with_hospital <- left_join(new_data, hospitals_msa, by = "msa")

write.csv(new_data_with_hospital, file = "priv_pay_data_with_hospital.csv")

```
